### ISSUE TITLE
stores migration error

### ISSUE THREAD

**Issue by EhabAmawi** [enanobots/m2-m1migration#1]
while I was trying to run stores migration, I faced this error.

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'old_magento.store_website' doesn't exist, query was: select website_id,code,name,sort_order,default_group_id,is_default
            from `mg_store_website`
                where `website_id` > 0
                and `website_id`
#0 /var/www/m2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#1 /var/www/m2/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#2 /var/www/m2/vendor/enanobots/m2-m1migration/src/Model/Import/Setup/SetupAbstract.php(103): Zend_Db_Adapter_Abstract->fetchAll()
#3 /var/www/m2/vendor/enanobots/m2-m1migration/src/Console/MigrationStores.php(82): Nanobots\MigrationTool\Model\Import\Setup\SetupAbstract->insertConfig()
#4 /var/www/m2/vendor/enanobots/m2-m1migration/src/Console/MigrationAbstract.php(92): Nanobots\MigrationTool\Console\MigrationStores->migrate()
#5 /var/www/m2/vendor/symfony/console/Command/Command.php(298): Nanobots\MigrationTool\Console\MigrationAbstract->execute()
#6 /var/www/m2/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#7 /var/www/m2/vendor/magento/framework/Interception/Interceptor.php(138): Nanobots\MigrationTool\Console\MigrationStores\Interceptor->___callParent()
#8 /var/www/m2/vendor/magento/framework/Interception/Interceptor.php(153): Nanobots\MigrationTool\Console\MigrationStores\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/m2/generated/code/Nanobots/MigrationTool/Console/MigrationStores/Interceptor.php(23): Nanobots\MigrationTool\Console\MigrationStores\Interceptor->___callPlugins()
#10 /var/www/cproducts/vendor/symfony/console/Application.php(1040): Nanobots\MigrationTool\Console\MigrationStores\Interceptor->run()
#11 /var/www/m2/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/m2/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 /var/www/cproducts/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#14 /var/www/m2/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
```

m2 version: 2.4.6
m1 version: 1.9.2.2

**Comment by enanobots** [comment]
This is related to this PR:
https://github.com/enanobots/m2-m1migration/pull/3
Closing this one :-)
